/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.medicaid.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CustomQuery service. Represents a row in the &quot;Medicaid_CustomQuery&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.medicaid.liferay.model.impl.CustomQueryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.medicaid.liferay.model.impl.CustomQueryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CustomQuery
 * @generated
 */
@ProviderType
public interface CustomQueryModel extends BaseModel<CustomQuery> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a custom query model instance should use the {@link CustomQuery} interface instead.
	 */

	/**
	 * Returns the primary key of this custom query.
	 *
	 * @return the primary key of this custom query
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this custom query.
	 *
	 * @param primaryKey the primary key of this custom query
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the sql key of this custom query.
	 *
	 * @return the sql key of this custom query
	 */
	@AutoEscape
	public String getSqlKey();

	/**
	 * Sets the sql key of this custom query.
	 *
	 * @param sqlKey the sql key of this custom query
	 */
	public void setSqlKey(String sqlKey);

	/**
	 * Returns the sql query of this custom query.
	 *
	 * @return the sql query of this custom query
	 */
	@AutoEscape
	public String getSqlQuery();

	/**
	 * Sets the sql query of this custom query.
	 *
	 * @param sqlQuery the sql query of this custom query
	 */
	public void setSqlQuery(String sqlQuery);

}