/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.medicaid.app.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Document service. Represents a row in the &quot;Medicaid_Document&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.medicaid.app.model.impl.DocumentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.medicaid.app.model.impl.DocumentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Document
 * @generated
 */
@ProviderType
public interface DocumentModel extends BaseModel<Document> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a document model instance should use the {@link Document} interface instead.
	 */

	/**
	 * Returns the primary key of this document.
	 *
	 * @return the primary key of this document
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this document.
	 *
	 * @param primaryKey the primary key of this document
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the document ID of this document.
	 *
	 * @return the document ID of this document
	 */
	public long getDocumentId();

	/**
	 * Sets the document ID of this document.
	 *
	 * @param documentId the document ID of this document
	 */
	public void setDocumentId(long documentId);

	/**
	 * Returns the doc name of this document.
	 *
	 * @return the doc name of this document
	 */
	@AutoEscape
	public String getDocName();

	/**
	 * Sets the doc name of this document.
	 *
	 * @param docName the doc name of this document
	 */
	public void setDocName(String docName);

	/**
	 * Returns the file ID of this document.
	 *
	 * @return the file ID of this document
	 */
	public long getFileId();

	/**
	 * Sets the file ID of this document.
	 *
	 * @param fileId the file ID of this document
	 */
	public void setFileId(long fileId);

	/**
	 * Returns the file url of this document.
	 *
	 * @return the file url of this document
	 */
	@AutoEscape
	public String getFileUrl();

	/**
	 * Sets the file url of this document.
	 *
	 * @param fileUrl the file url of this document
	 */
	public void setFileUrl(String fileUrl);

	/**
	 * Returns the patient ID of this document.
	 *
	 * @return the patient ID of this document
	 */
	public long getPatientId();

	/**
	 * Sets the patient ID of this document.
	 *
	 * @param patientId the patient ID of this document
	 */
	public void setPatientId(long patientId);

	/**
	 * Returns the create date of this document.
	 *
	 * @return the create date of this document
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this document.
	 *
	 * @param createDate the create date of this document
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this document.
	 *
	 * @return the created by of this document
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this document.
	 *
	 * @param createdBy the created by of this document
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the modified date of this document.
	 *
	 * @return the modified date of this document
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this document.
	 *
	 * @param modifiedDate the modified date of this document
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this document.
	 *
	 * @return the modified by of this document
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this document.
	 *
	 * @param modifiedBy the modified by of this document
	 */
	public void setModifiedBy(String modifiedBy);

}