/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.medicaid.app.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Facility service. Represents a row in the &quot;Medicaid_Facility&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.medicaid.app.model.impl.FacilityModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.medicaid.app.model.impl.FacilityImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Facility
 * @generated
 */
@ProviderType
public interface FacilityModel extends BaseModel<Facility> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a facility model instance should use the {@link Facility} interface instead.
	 */

	/**
	 * Returns the primary key of this facility.
	 *
	 * @return the primary key of this facility
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this facility.
	 *
	 * @param primaryKey the primary key of this facility
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the facility ID of this facility.
	 *
	 * @return the facility ID of this facility
	 */
	public long getFacilityId();

	/**
	 * Sets the facility ID of this facility.
	 *
	 * @param facilityId the facility ID of this facility
	 */
	public void setFacilityId(long facilityId);

	/**
	 * Returns the name of this facility.
	 *
	 * @return the name of this facility
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this facility.
	 *
	 * @param name the name of this facility
	 */
	public void setName(String name);

	/**
	 * Returns the address of this facility.
	 *
	 * @return the address of this facility
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this facility.
	 *
	 * @param address the address of this facility
	 */
	public void setAddress(String address);

	/**
	 * Returns the city of this facility.
	 *
	 * @return the city of this facility
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this facility.
	 *
	 * @param city the city of this facility
	 */
	public void setCity(String city);

	/**
	 * Returns the state of this facility.
	 *
	 * @return the state of this facility
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this facility.
	 *
	 * @param state the state of this facility
	 */
	public void setState(String state);

	/**
	 * Returns the zipcode of this facility.
	 *
	 * @return the zipcode of this facility
	 */
	@AutoEscape
	public String getZipcode();

	/**
	 * Sets the zipcode of this facility.
	 *
	 * @param zipcode the zipcode of this facility
	 */
	public void setZipcode(String zipcode);

	/**
	 * Returns the phone number of this facility.
	 *
	 * @return the phone number of this facility
	 */
	public long getPhoneNumber();

	/**
	 * Sets the phone number of this facility.
	 *
	 * @param phoneNumber the phone number of this facility
	 */
	public void setPhoneNumber(long phoneNumber);

	/**
	 * Returns the fax number of this facility.
	 *
	 * @return the fax number of this facility
	 */
	@AutoEscape
	public String getFaxNumber();

	/**
	 * Sets the fax number of this facility.
	 *
	 * @param faxNumber the fax number of this facility
	 */
	public void setFaxNumber(String faxNumber);

	/**
	 * Returns the email of this facility.
	 *
	 * @return the email of this facility
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this facility.
	 *
	 * @param email the email of this facility
	 */
	public void setEmail(String email);

	/**
	 * Returns the point of contact of this facility.
	 *
	 * @return the point of contact of this facility
	 */
	@AutoEscape
	public String getPointOfContact();

	/**
	 * Sets the point of contact of this facility.
	 *
	 * @param pointOfContact the point of contact of this facility
	 */
	public void setPointOfContact(String pointOfContact);

	/**
	 * Returns the create date of this facility.
	 *
	 * @return the create date of this facility
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this facility.
	 *
	 * @param createDate the create date of this facility
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this facility.
	 *
	 * @return the created by of this facility
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this facility.
	 *
	 * @param createdBy the created by of this facility
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the modified date of this facility.
	 *
	 * @return the modified date of this facility
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this facility.
	 *
	 * @param modifiedDate the modified date of this facility
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this facility.
	 *
	 * @return the modified by of this facility
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this facility.
	 *
	 * @param modifiedBy the modified by of this facility
	 */
	public void setModifiedBy(String modifiedBy);

}