/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.medicaid.app.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FacilityAdmin service. Represents a row in the &quot;Medicaid_FacilityAdmin&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.medicaid.app.model.impl.FacilityAdminModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.medicaid.app.model.impl.FacilityAdminImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FacilityAdmin
 * @generated
 */
@ProviderType
public interface FacilityAdminModel extends BaseModel<FacilityAdmin> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a facility admin model instance should use the {@link FacilityAdmin} interface instead.
	 */

	/**
	 * Returns the primary key of this facility admin.
	 *
	 * @return the primary key of this facility admin
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this facility admin.
	 *
	 * @param primaryKey the primary key of this facility admin
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the user name of this facility admin.
	 *
	 * @return the user name of this facility admin
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this facility admin.
	 *
	 * @param userName the user name of this facility admin
	 */
	public void setUserName(String userName);

	/**
	 * Returns the email of this facility admin.
	 *
	 * @return the email of this facility admin
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this facility admin.
	 *
	 * @param email the email of this facility admin
	 */
	public void setEmail(String email);

	/**
	 * Returns the first name of this facility admin.
	 *
	 * @return the first name of this facility admin
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this facility admin.
	 *
	 * @param firstName the first name of this facility admin
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this facility admin.
	 *
	 * @return the last name of this facility admin
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this facility admin.
	 *
	 * @param lastName the last name of this facility admin
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the phone number of this facility admin.
	 *
	 * @return the phone number of this facility admin
	 */
	public long getPhoneNumber();

	/**
	 * Sets the phone number of this facility admin.
	 *
	 * @param phoneNumber the phone number of this facility admin
	 */
	public void setPhoneNumber(long phoneNumber);

	/**
	 * Returns the title of this facility admin.
	 *
	 * @return the title of this facility admin
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this facility admin.
	 *
	 * @param title the title of this facility admin
	 */
	public void setTitle(String title);

	/**
	 * Returns the facility IDs of this facility admin.
	 *
	 * @return the facility IDs of this facility admin
	 */
	@AutoEscape
	public String getFacilityIds();

	/**
	 * Sets the facility IDs of this facility admin.
	 *
	 * @param facilityIds the facility IDs of this facility admin
	 */
	public void setFacilityIds(String facilityIds);

	/**
	 * Returns the create date of this facility admin.
	 *
	 * @return the create date of this facility admin
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this facility admin.
	 *
	 * @param createDate the create date of this facility admin
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this facility admin.
	 *
	 * @return the created by of this facility admin
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this facility admin.
	 *
	 * @param createdBy the created by of this facility admin
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the modified date of this facility admin.
	 *
	 * @return the modified date of this facility admin
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this facility admin.
	 *
	 * @param modifiedDate the modified date of this facility admin
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this facility admin.
	 *
	 * @return the modified by of this facility admin
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this facility admin.
	 *
	 * @param modifiedBy the modified by of this facility admin
	 */
	public void setModifiedBy(String modifiedBy);

}