/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.medicaid.app.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Note service. Represents a row in the &quot;Medicaid_Note&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.medicaid.app.model.impl.NoteModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.medicaid.app.model.impl.NoteImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Note
 * @generated
 */
@ProviderType
public interface NoteModel extends BaseModel<Note> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a note model instance should use the {@link Note} interface instead.
	 */

	/**
	 * Returns the primary key of this note.
	 *
	 * @return the primary key of this note
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this note.
	 *
	 * @param primaryKey the primary key of this note
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the note ID of this note.
	 *
	 * @return the note ID of this note
	 */
	public long getNoteId();

	/**
	 * Sets the note ID of this note.
	 *
	 * @param noteId the note ID of this note
	 */
	public void setNoteId(long noteId);

	/**
	 * Returns the referral ID of this note.
	 *
	 * @return the referral ID of this note
	 */
	public Long getReferralId();

	/**
	 * Sets the referral ID of this note.
	 *
	 * @param referralId the referral ID of this note
	 */
	public void setReferralId(Long referralId);

	/**
	 * Returns the comment date of this note.
	 *
	 * @return the comment date of this note
	 */
	public Date getCommentDate();

	/**
	 * Sets the comment date of this note.
	 *
	 * @param commentDate the comment date of this note
	 */
	public void setCommentDate(Date commentDate);

	/**
	 * Returns the comments of this note.
	 *
	 * @return the comments of this note
	 */
	@AutoEscape
	public String getComments();

	/**
	 * Sets the comments of this note.
	 *
	 * @param comments the comments of this note
	 */
	public void setComments(String comments);

	/**
	 * Returns the create date of this note.
	 *
	 * @return the create date of this note
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this note.
	 *
	 * @param createDate the create date of this note
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this note.
	 *
	 * @return the created by of this note
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this note.
	 *
	 * @param createdBy the created by of this note
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the modified date of this note.
	 *
	 * @return the modified date of this note
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this note.
	 *
	 * @param modifiedDate the modified date of this note
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this note.
	 *
	 * @return the modified by of this note
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this note.
	 *
	 * @param modifiedBy the modified by of this note
	 */
	public void setModifiedBy(String modifiedBy);

}