/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.medicaid.app.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Referral service. Represents a row in the &quot;Medicaid_Referral&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.medicaid.app.model.impl.ReferralModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.medicaid.app.model.impl.ReferralImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Referral
 * @generated
 */
@ProviderType
public interface ReferralModel extends BaseModel<Referral> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a referral model instance should use the {@link Referral} interface instead.
	 */

	/**
	 * Returns the primary key of this referral.
	 *
	 * @return the primary key of this referral
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this referral.
	 *
	 * @param primaryKey the primary key of this referral
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the referral ID of this referral.
	 *
	 * @return the referral ID of this referral
	 */
	public long getReferralId();

	/**
	 * Sets the referral ID of this referral.
	 *
	 * @param referralId the referral ID of this referral
	 */
	public void setReferralId(long referralId);

	/**
	 * Returns the date referred of this referral.
	 *
	 * @return the date referred of this referral
	 */
	public Date getDateReferred();

	/**
	 * Sets the date referred of this referral.
	 *
	 * @param dateReferred the date referred of this referral
	 */
	public void setDateReferred(Date dateReferred);

	/**
	 * Returns the submit date of this referral.
	 *
	 * @return the submit date of this referral
	 */
	public Date getSubmitDate();

	/**
	 * Sets the submit date of this referral.
	 *
	 * @param submitDate the submit date of this referral
	 */
	public void setSubmitDate(Date submitDate);

	/**
	 * Returns the approved date of this referral.
	 *
	 * @return the approved date of this referral
	 */
	public Date getApprovedDate();

	/**
	 * Sets the approved date of this referral.
	 *
	 * @param approvedDate the approved date of this referral
	 */
	public void setApprovedDate(Date approvedDate);

	/**
	 * Returns the pending date of this referral.
	 *
	 * @return the pending date of this referral
	 */
	public Date getPendingDate();

	/**
	 * Sets the pending date of this referral.
	 *
	 * @param pendingDate the pending date of this referral
	 */
	public void setPendingDate(Date pendingDate);

	/**
	 * Returns the status of this referral.
	 *
	 * @return the status of this referral
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this referral.
	 *
	 * @param status the status of this referral
	 */
	public void setStatus(String status);

	/**
	 * Returns the coc email sent of this referral.
	 *
	 * @return the coc email sent of this referral
	 */
	@AutoEscape
	public String getCocEmailSent();

	/**
	 * Sets the coc email sent of this referral.
	 *
	 * @param cocEmailSent the coc email sent of this referral
	 */
	public void setCocEmailSent(String cocEmailSent);

	/**
	 * Returns the res liability of this referral.
	 *
	 * @return the res liability of this referral
	 */
	public double getResLiability();

	/**
	 * Sets the res liability of this referral.
	 *
	 * @param resLiability the res liability of this referral
	 */
	public void setResLiability(double resLiability);

	/**
	 * Returns the email sent due date of this referral.
	 *
	 * @return the email sent due date of this referral
	 */
	public Date getEmailSentDueDate();

	/**
	 * Sets the email sent due date of this referral.
	 *
	 * @param emailSentDueDate the email sent due date of this referral
	 */
	public void setEmailSentDueDate(Date emailSentDueDate);

	/**
	 * Returns the facility admin of this referral.
	 *
	 * @return the facility admin of this referral
	 */
	@AutoEscape
	public String getFacilityAdmin();

	/**
	 * Sets the facility admin of this referral.
	 *
	 * @param facilityAdmin the facility admin of this referral
	 */
	public void setFacilityAdmin(String facilityAdmin);

	/**
	 * Returns the facilities of this referral.
	 *
	 * @return the facilities of this referral
	 */
	@AutoEscape
	public String getFacilities();

	/**
	 * Sets the facilities of this referral.
	 *
	 * @param facilities the facilities of this referral
	 */
	public void setFacilities(String facilities);

	/**
	 * Returns the patient ID of this referral.
	 *
	 * @return the patient ID of this referral
	 */
	public long getPatientId();

	/**
	 * Sets the patient ID of this referral.
	 *
	 * @param patientId the patient ID of this referral
	 */
	public void setPatientId(long patientId);

	/**
	 * Returns the note ID of this referral.
	 *
	 * @return the note ID of this referral
	 */
	public long getNoteId();

	/**
	 * Sets the note ID of this referral.
	 *
	 * @param noteId the note ID of this referral
	 */
	public void setNoteId(long noteId);

	/**
	 * Returns the create date of this referral.
	 *
	 * @return the create date of this referral
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this referral.
	 *
	 * @param createDate the create date of this referral
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this referral.
	 *
	 * @return the created by of this referral
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this referral.
	 *
	 * @param createdBy the created by of this referral
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the modified date of this referral.
	 *
	 * @return the modified date of this referral
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this referral.
	 *
	 * @param modifiedDate the modified date of this referral
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this referral.
	 *
	 * @return the modified by of this referral
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this referral.
	 *
	 * @param modifiedBy the modified by of this referral
	 */
	public void setModifiedBy(String modifiedBy);

}