/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.medicaid.app.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.medicaid.app.model.FacilityAdmin;
import com.medicaid.app.service.FacilityAdminLocalService;
import com.medicaid.app.service.persistence.FacilityAdminPersistence;
import com.medicaid.app.service.persistence.FacilityPersistence;
import com.medicaid.app.service.persistence.NotePersistence;
import com.medicaid.app.service.persistence.PatientPersistence;
import com.medicaid.app.service.persistence.ReferralPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the facility admin local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.medicaid.app.service.impl.FacilityAdminLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.medicaid.app.service.impl.FacilityAdminLocalServiceImpl
 * @generated
 */
public abstract class FacilityAdminLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, FacilityAdminLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>FacilityAdminLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.medicaid.app.service.FacilityAdminLocalServiceUtil</code>.
	 */

	/**
	 * Adds the facility admin to the database. Also notifies the appropriate model listeners.
	 *
	 * @param facilityAdmin the facility admin
	 * @return the facility admin that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public FacilityAdmin addFacilityAdmin(FacilityAdmin facilityAdmin) {
		facilityAdmin.setNew(true);

		return facilityAdminPersistence.update(facilityAdmin);
	}

	/**
	 * Creates a new facility admin with the primary key. Does not add the facility admin to the database.
	 *
	 * @param userName the primary key for the new facility admin
	 * @return the new facility admin
	 */
	@Override
	@Transactional(enabled = false)
	public FacilityAdmin createFacilityAdmin(String userName) {
		return facilityAdminPersistence.create(userName);
	}

	/**
	 * Deletes the facility admin with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param userName the primary key of the facility admin
	 * @return the facility admin that was removed
	 * @throws PortalException if a facility admin with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public FacilityAdmin deleteFacilityAdmin(String userName)
		throws PortalException {

		return facilityAdminPersistence.remove(userName);
	}

	/**
	 * Deletes the facility admin from the database. Also notifies the appropriate model listeners.
	 *
	 * @param facilityAdmin the facility admin
	 * @return the facility admin that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public FacilityAdmin deleteFacilityAdmin(FacilityAdmin facilityAdmin) {
		return facilityAdminPersistence.remove(facilityAdmin);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			FacilityAdmin.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return facilityAdminPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.medicaid.app.model.impl.FacilityAdminModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return facilityAdminPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.medicaid.app.model.impl.FacilityAdminModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return facilityAdminPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return facilityAdminPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return facilityAdminPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public FacilityAdmin fetchFacilityAdmin(String userName) {
		return facilityAdminPersistence.fetchByPrimaryKey(userName);
	}

	/**
	 * Returns the facility admin with the primary key.
	 *
	 * @param userName the primary key of the facility admin
	 * @return the facility admin
	 * @throws PortalException if a facility admin with the primary key could not be found
	 */
	@Override
	public FacilityAdmin getFacilityAdmin(String userName)
		throws PortalException {

		return facilityAdminPersistence.findByPrimaryKey(userName);
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return facilityAdminPersistence.create((String)primaryKeyObj);
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return facilityAdminLocalService.deleteFacilityAdmin(
			(FacilityAdmin)persistedModel);
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return facilityAdminPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the facility admins.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.medicaid.app.model.impl.FacilityAdminModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of facility admins
	 * @param end the upper bound of the range of facility admins (not inclusive)
	 * @return the range of facility admins
	 */
	@Override
	public List<FacilityAdmin> getFacilityAdmins(int start, int end) {
		return facilityAdminPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of facility admins.
	 *
	 * @return the number of facility admins
	 */
	@Override
	public int getFacilityAdminsCount() {
		return facilityAdminPersistence.countAll();
	}

	/**
	 * Updates the facility admin in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param facilityAdmin the facility admin
	 * @return the facility admin that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public FacilityAdmin updateFacilityAdmin(FacilityAdmin facilityAdmin) {
		return facilityAdminPersistence.update(facilityAdmin);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			FacilityAdminLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		facilityAdminLocalService = (FacilityAdminLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return FacilityAdminLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return FacilityAdmin.class;
	}

	protected String getModelClassName() {
		return FacilityAdmin.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = facilityAdminPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected FacilityPersistence facilityPersistence;

	protected FacilityAdminLocalService facilityAdminLocalService;

	@Reference
	protected FacilityAdminPersistence facilityAdminPersistence;

	@Reference
	protected NotePersistence notePersistence;

	@Reference
	protected PatientPersistence patientPersistence;

	@Reference
	protected ReferralPersistence referralPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}